server:
  port: 8000

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: false
      settings:
        web-allow-others: false
